### ISSUE TITLE
Doesn't identify a SlowBuffer as a buffer

### ISSUE THREAD

**Issue by phated** [feross/is-buffer#2] opened 2016-02-26 20:44 UTC
I just noticed that if a SlowBuffer is passed to this, it isn't identified as a buffer; however, node's Buffer.isBuffer correctly identifies it as a buffer.

**Comment by feross** [comment] 2016-02-27 21:29
@phated Is this is a node.js or browserify `SlowBuffer`? If node.js, what version are you using?

Can you share sample code where you expect this package to return `true`?

**Comment by feross** [comment] 2016-02-27 21:31
I can't reproduce. In node v4 and browserify, this works as expected:

``` js
var isBuffer = require('is-buffer')
isBuffer(new require('buffer').SlowBuffer(1000)) // true
```

**Comment by feross** [comment] 2016-03-07 20:21
@phated Ping.

**Comment by phated** [comment] 2016-03-07 21:54
Sorry for the delay.  I just tried your example in node 0.10 and it fails.

**Comment by phated** [comment] 2016-03-07 21:56
Looks like it is working in >=0.12 (which is weird, because our vinyl-fs tests were failing on that version too).

**Comment by feross** [comment] 2016-03-07 22:04
Ah, this is because `SlowBuffer` is a different class in node 0.10 and there's no `SlowBuffer.isBuffer` method.

**Comment by feross** [comment] 2016-03-07 22:04
Have you considered just dropping node 0.10 support? It's going to be completely unsupported (even no security updates) in October 2016.

**Comment by phated** [comment] 2016-03-07 22:06
Nope. It is still maintained, has tons of users and I personally see it as the most stable version of node (still).

**Comment by phated** [comment] 2016-03-07 22:07
If you don't plan to support it, can you mark the package with `engines` so devs will be warned when attempting to use it?  I shipped a broken version of vinyl-fs due to this problem.

**Comment by phated** [comment] 2016-03-07 22:09
Another note: `Buffer.isBuffer()` in node 0.10 correctly identifies the SlowBuffer, which is what I switched to.

**Comment by feross** [comment] 2016-03-07 22:13
If you're in node, you can of course use `Buffer.isBuffer()`. The primary purpose of this package is to avoid including the whole `Buffer` package in your browser javascript bundle if you just need to check if something is a buffer because normally it will be included if you do `Buffer.isBuffer()`.

Is `vinyl-fs` supposed to work with browserify?

**Comment by phated** [comment] 2016-03-07 22:23
@feross yeah, in 2.0 removed the `watch` method so there were no native modules and we recently received an issue related to someone browserifying the package.

**Comment by feross** [comment] 2016-03-07 22:34
If you're not carefully curating your node package dependencies to ensure that no one is calling `require('buffer')` or using the `Buffer` global, then the whole buffer package will end up in the browser bundle anyway, so I'd just continue using `Buffer.isBuffer()`.

Thanks for opening the issue and sorry for breaking your package.

**Comment by feross** [comment] 2016-03-07 22:35
For example, one of your dependencies [uses buffer](https://github.com/substack/node-buffer-equal/blob/master/index.js#L1) here.

**Closed as completed by feross** 2016-03-07 22:34 UTC
Labels: question

**Comment by phated** [comment] 2016-03-07 22:37
Thanks.  I really hope you update the package.json to note the engine dependency.  You don't have to use `engineStrict` but the warning would be really helpful.

**Comment by feross** [comment] 2016-03-07 22:45
Sure thing.
